import org.jetbrains.kotlin.gradle.ExperimentalWasmDsl

// Browser harness and npm packaging reference. Not published to Maven and not in the ABI gate.
//
//   ./gradlew :sample-web:wasmJsBrowserDevelopmentRun   # harness in a browser, with reload
//   ./gradlew :sample-web:npmPackage                    # build/npm: the @aardarch/aardink-web package
//
// This module is what a product's own web-editor module looks like: it depends on
// :editor-web + :languages, declares the executable, owns the @JsExport surface (Exports.kt,
// the running copy of editor-web's ExportsTemplate.kt) and turns the result into an npm
// package. See docs/WEB_INTEGRATION.md.

val jvmVersionInt =
    libs.versions.jvm
        .get()
        .toInt()

plugins {
    alias(libs.plugins.plugin.kotlin.multiplatform)
    alias(libs.plugins.plugin.compose.multiplatform)
    alias(libs.plugins.plugin.kotlin.compose)
    alias(libs.plugins.plugin.spotless)
}

val versionName = providers.gradleProperty("VERSION_NAME")

// ── BuildInfo.VERSION for aardinkVersion() ────────────────────────────────────
val generateBuildInfo by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/buildInfo/kotlin")
    val version = versionName
    inputs.property("version", version)
    outputs.dir(outputDir)
    doLast {
        val file = outputDir.get().file("com/aardarch/aardink/sampleweb/BuildInfo.kt").asFile
        file.parentFile.mkdirs()
        file.writeText(
            """
            |package com.aardarch.aardink.sampleweb
            |
            |/** Generated by :sample-web:generateBuildInfo from VERSION_NAME. */
            |internal object BuildInfo {
            |    const val VERSION: String = "${version.get()}"
            |}
            |
            """.trimMargin(),
        )
    }
}

kotlin {
    jvmToolchain(jvmVersionInt)

    @OptIn(ExperimentalWasmDsl::class)
    wasmJs {
        // The .mjs/.wasm file names, and so the npm package's kotlin/aardink-web.mjs.
        outputModuleName.set("aardink-web")
        browser {
            commonWebpackConfig {
                outputFileName = "sample-web.js"
            }
        }
        binaries.executable()
    }

    sourceSets {
        named("wasmJsMain") {
            kotlin.srcDir(generateBuildInfo)
            dependencies {
                implementation(project(":editor-web"))
                implementation(project(":languages"))
            }
        }
    }
}

// ── npm package ───────────────────────────────────────────────────────────────
// The raw ES modules, not the webpack bundle: a consuming app's own bundler resolves the one
// bare import in them (@js-joda/core, via Compose's kotlinx-datetime) and emits the .wasm files
// and the font from their `new URL(..., import.meta.url)` references.

val kotlinOutput = tasks.named("wasmJsProductionExecutableCompileSync")
val processedResources = tasks.named("wasmJsProcessResources")
val generatedPackageJson = tasks.named("wasmJsPackageJson")

val npmPackageDir = layout.buildDirectory.dir("npm")

val npmPackage by tasks.registering(Sync::class) {
    group = "distribution"
    description = "Assembles the @aardarch/aardink-web npm package in build/npm."

    val version = versionName
    val kotlinPackageJson = generatedPackageJson.map { it.outputs.files.singleFile }
    inputs.property("version", version)
    inputs.files(kotlinPackageJson)

    // The `dependencies` object of the package.json Kotlin generates for this module, so the npm
    // package declares exactly what the compiled .mjs imports. A local lambda, not a script-level
    // function: the configuration cache cannot serialize a reference to the script object.
    val kotlinDependencies: (File) -> String = { packageJson ->
        Regex("\"dependencies\"\\s*:\\s*(\\{[^}]*\\})")
            .find(packageJson.readText())
            ?.groupValues
            ?.get(1)
            ?.replace(Regex("\\s+"), " ")
            ?: "{}"
    }

    into(npmPackageDir)
    from("src/npm") {
        exclude("package.json")
        filter { line -> line.replace("@VERSION@", version.get()) }
    }
    from("src/npm/package.json") {
        filter { line ->
            line
                .replace("@VERSION@", version.get())
                .replace("\"@DEPENDENCIES@\"", kotlinDependencies(kotlinPackageJson.get()))
        }
    }
    from(rootProject.file("editor-web/JETBRAINS_MONO_OFL.txt"))
    into("kotlin") {
        // Already holds skiko.mjs/skiko.wasm next to the module, which is where it imports them.
        from(kotlinOutput) {
            include("*.mjs", "*.wasm")
        }
        from(processedResources) {
            include("composeResources/**")
        }
    }
}

// ── Keep Exports.kt in step with the compiled template ──────────────────────────
// The template in editor-web's tests is what consumers copy; this module's Exports.kt is the
// running copy index.js calls. They must export the same functions with the same parameters.
val verifyExportsMatchTemplate by tasks.registering {
    group = "verification"
    description = "Fails if Exports.kt and editor-web's ExportsTemplate.kt export different functions."
    val template = rootProject.file("editor-web/src/wasmJsTest/kotlin/com/aardarch/aardink/web/ExportsTemplate.kt")
    val running = file("src/wasmJsMain/kotlin/com/aardarch/aardink/sampleweb/Exports.kt")
    inputs.files(template, running)
    doLast {
        val signature = Regex("""fun (aardink\w+\([^)]*\))""")

        fun exportsOf(file: File) = signature.findAll(file.readText()).map { it.groupValues[1] }.toSortedSet()
        val expected = exportsOf(template)
        val actual = exportsOf(running)
        check(expected == actual) {
            "Exports.kt has drifted from ExportsTemplate.kt.\n  only in template: ${expected - actual}\n  only in Exports.kt: ${actual - expected}"
        }
    }
}

tasks.named("check") { dependsOn(verifyExportsMatchTemplate) }

spotless {
    kotlin {
        target("src/**/*.kt")
        ktlint().editorConfigOverride(
            mapOf(
                "ktlint_standard_function-naming" to "disabled",
                "ktlint_standard_no-wildcard-imports" to "disabled",
                "ktlint_standard_no-empty-file" to "disabled",
            ),
        )
        trimTrailingWhitespace()
        endWithNewline()
    }
    kotlinGradle {
        target("*.gradle.kts")
        ktlint()
    }
}
